config/routes.rb
Rails.application.routes.draw do
  resources :trackers
  #get 'home/index'
  get 'home/main'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tracker.rb
class Tracker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def main
  end
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  before_action :set_tracker, only: %i[ show edit update destroy ]

  # GET /trackers or /trackers.json
  def index
    @trackers = Tracker.all
  end

  # GET /trackers/1 or /trackers/1.json
  def show
  end

  # GET /trackers/new
  def new
    @tracker = Tracker.new
  end

  # GET /trackers/1/edit
  def edit
  end

  # POST /trackers or /trackers.json
  def create
    @tracker = Tracker.new(tracker_params)

    respond_to do |format|
      if @tracker.save
        format.html { redirect_to tracker_url(@tracker), notice: "Tracker was successfully created." }
        format.json { render :show, status: :created, location: @tracker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackers/1 or /trackers/1.json
  def update
    respond_to do |format|
      if @tracker.update(tracker_params)
        format.html { redirect_to tracker_url(@tracker), notice: "Tracker was successfully updated." }
        format.json { render :show, status: :ok, location: @tracker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackers/1 or /trackers/1.json
  def destroy
    @tracker.destroy

    respond_to do |format|
      format.html { redirect_to trackers_url, notice: "Tracker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tracker
      @tracker = Tracker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tracker_params
      params.require(:tracker).permit(:date, :excercise, :reps, :weight, :goal)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #938e93">
  <div class="container-fluid">
    <a class="navbar-brand">The Lab</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'Home', root_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to 'Information', home_main_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to 'Tracker', trackers_path, class:"nav-link"%>
        </li>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<body>
<h1>The Lab</h1>
<p>Welcome to The Lab, your personal gym tracker application</p>
</body>

app/views/home/main.html.erb
<h1>Welcome to the information page!</h1>
<p>Here you can learn about different exercises to improve your workout routine!</p>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Smith Machine Incline Press</h5>
          <h6 class="card-text">Target: Upper Chest</h6>
          <p class="card-text">The incline press with smith machine is a fantastic upper chest workout which leads to great stimulation and
          activation, a slow and controlled motion will lead to a great squeeze to work the upper chest</p>
        </div>
      </div>
    </div>

    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lat Pull Down</h5>
          <h6 class="card-text">Target: Lats</h6>
          <p class="card-text">The lateral pull down is the go-to machine to build a broader back, keeping your chin back and back straight then
          bringing the bar staight down to your chest is vital to target the correct muscle.</p>
        </div>
      </div>
    </div>

    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Dips</h5>
          <h6 class="card-text">Target: Triceps</h6>
          <p class="card-text">A common misconception is that you need big biceps for big arms. But did you know the tricep is the biggest muscle on your arm?
          It is incredibly important to train triceps often on an arm day. A great exercise for this is dips.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Leg Press</h5>
          <h6 class="card-text">Target: Quads</h6>
          <p class="card-text">The common leg press is a staple in building your quads, allowing for more flexibility and strength 
          so you can run and walk much easier and faster. It is important when doing a leg press to keep your feet positioned low, rather than up high
          as this will cause you to work your glutes instead of quads.</p>
        </div>
      </div>
    </div>

    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lateral Raises</h5>
          <h6 class="card-text">Target: Shoulder</h6>
          <p class="card-text">The lateral raise is one of the most common shoulder excercises due to its simplicity and effectivness. Pushing out hard and controlling
          your eccentric movements creates great stimulation in the muscle.</p>
        </div>
      </div>
    </div>

    <div class="col-md-4 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Stairmaster</h5>
          <h6 class="card-text">Target: Cardiovascular System</h6>
          <p class="card-text">One of the most important favours you could do to your body is cardio. The stairmaster is a fantastic machine that simulates
            using the stairs, listening to music or a podcast while doing this makes it more enjoyable.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-dark" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<body style="background-color: #aba7ab;">
  <head>
  <title>GymApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <body>

    <%= render 'home/header' %>
    <div class="container">

    <br/>
    <% if notice %>
    <%= render 'layouts/alerts' %>
    <% end %>

    <%= yield %>
    </div>
  </body>
  </body>
  </body>
</html>

app/views/trackers/_form.html.erb
<%= form_with(model: tracker, class: "needs-validation", novalidate: true) do |form| %>
  <% if tracker.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(tracker.errors.count, "error") %> prohibited this tracker from being saved:</h2>

      <ul>
        <% tracker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-2">
    <%= form.label :date, class: "form-label", style: "font-size: 18px;"%>
    <%= form.text_field :date, class: "form-control", required: true, style: "background-color: #d8d6d8;"%>
  </div>

  <div class="mb-2">
    <%= form.label :excercise, class: "form-label", style: "font-size: 18px;" %>
    <%= form.text_field :excercise, class: "form-control", required: true, style: "background-color: #d8d6d8;" %>
  </div>

  <div class="mb-2">
    <%= form.label :reps, class: "form-label", style: "font-size: 18px;" %>
    <%= form.text_field :reps, class: "form-control", required: true, style: "background-color: #d8d6d8;" %>
  </div>

  <div class="mb-2">
    <%= form.label :weight, class: "form-label", style: "font-size: 18px;" %>
    <%= form.text_field :weight, class: "form-control", required: true, style: "background-color: #d8d6d8;" %>
  </div>

  <div class="mb-2">
    <%= form.label :goal, class: "form-label", style: "font-size: 18px;" %>
    <%= form.text_field :goal, class: "form-control", required: true, style: "background-color: #d8d6d8;" %>
  </div>

  <div class="mb-2">
    <%= form.submit "Save", class: "btn btn-dark" %>
  </div>
<% end %>

app/views/trackers/_tracker.html.erb
<div class="jumbotron" style="background:#aba7ab !important">
  <h1 class="display-4">Exercise Tracker</h1>
  <p class="lead">Welcome to the view page, where you can view your progress, edit, or delete an exercise.</p>
  <hr class="my-4">
  <div id="<%= dom_id tracker %>">
    <dl class="row">
      <dt class="col-sm-3 lead">Date</dt>
      <dd class="col-sm-9 lead"><strong><%= tracker.date %></strong></dd>

      <dt class="col-sm-3 lead">Exercise</dt>
      <dd class="col-sm-9 lead"><strong><%= tracker.excercise %></strong></dd>

      <dt class="col-sm-3 lead">Sets/Reps</dt>
      <dd class="col-sm-9 lead"><strong><%= tracker.reps %></strong></dd>

      <dt class="col-sm-3 lead">Weight</dt>
      <dd class="col-sm-9 lead"><strong><%= tracker.weight %></strong></dd>

      <dt class="col-sm-3 lead">Goal</dt>
      <dd class="col-sm-9 lead"><strong><%= tracker.goal %></strong></dd>
    </dl>
    
  </div>
</div>
<dd class="col-sm-9">
<div class="btn-group">
  <div class="m-1"><%= link_to "Edit", edit_tracker_path(@tracker), class: "btn btn-dark" %></div>
  <div class="m-1"><%= button_to "Delete", @tracker, method: :delete, class: "btn btn-dark" %></div>
  <div class="m-1"><%= link_to "Return to main page", trackers_path, class:"btn btn-dark" %></div>
</div>
</dd>

app/views/trackers/edit.html.erb
<h1>Editing tracker</h1>

<%= render "form", tracker: @tracker %>

<br>

<div>
  <%= link_to "View", @tracker, class:"btn btn-dark" %>
  <%= link_to "Return to main page", trackers_path, class:"btn btn-dark" %>
</div>

app/views/trackers/index.html.erb
<h1>Gym Tracker</h1>
<p>Welcome to the main page, here you can view your exercises, your current weight for that exercise and your goal.</p>

<div id="trackers-table">
  <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Exercise</th>
        <th scope="col">Reps</th>
        <th scope="col">Weight</th>
        <th scope="col">Goal</th>
        <th scope="col">View</th>
      </tr>
    </thead>
    <tbody>
      <% @trackers.each do |tracker| %>
        <tr>
          <td><%= tracker.date %></td>
          <td><%= tracker.excercise %></td>
          <td><%= tracker.reps %></td>
          <td><%= tracker.weight %></td>
          <td><%= tracker.goal %></td>
          <td><%= link_to "View", tracker, class:"btn btn-dark" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Create new tracker", new_tracker_path, class:"btn btn-dark" %>

app/views/trackers/new.html.erb
<h1>New tracker</h1>

<%= render "form", tracker: @tracker %>

<div>
  <%= link_to "Return to main page", trackers_path, class:"btn btn-dark" %>
</div>

app/views/trackers/show.html.erb
<%= render @tracker %>
<div> 
</div>